### ISSUE TITLE
Required Improvment

### ISSUE THREAD

**Issue by johnusername** [JoelGMSec/EvilnoVNC#1]
@JoelGMSec edit index.html to not require these parameters in the url (autoconnect=true&password=false) + add "&resize=remote". (embedded too).
Page name need improvment 
read this writeup 
https://fhlipzero.io/blogs/6_noVNC/noVNC.html

It would be a great improvement if your script first started an ngnix or apache server, with https (let's encrypt) certificate to determine useragent and victim resolution and then open a custom dynamic session based on the grabbed resolution.

**Comment by JoelGMSec** [comment]
Hi!

I have just solved the parameter problem (and others).

The rest of the things are currently in the to-do, so I consider the issue solved.

Thanks for using EvilnoVNC :)


Regards!
