### ISSUE TITLE
Help Guys  ln: /usr/bin/python: File exists

### ISSUE THREAD

**Issue by chromeheartbeat** [JoelGMSec/EvilnoVNC#11]
I have just downloaded 2022 kali Linux and I have git-clone and built docker manually. 
Below is what I'm getting every time I repeat the process of building docker manually

OK: 861 MiB in 299 packages

**ln: /usr/bin/python: File exists**

The command '/bin/sh -c apk add sudo bash xfce4 xvfb xdpyinfo lightdm-gtk-greeter x11vnc xfce4-terminal chromium python3 py3-pip git openssl curl gcc libc-dev python3-dev &&     ln -s /usr/bin/python3 /usr/bin/python &&     echo 'CHROMIUM_FLAGS="--disable-gpu --disable-software-rasterizer --disable-dev-shm-usage --kiosk --no-sandbox --password-store=basic"' >> /etc/chromium/chromium.conf &&     dbus-uuidgen > /var/lib/dbus/machine-id' returned a non-zero code: 1

**Comment by Weesary** [comment]
Solution:
![imagen](https://user-images.githubusercontent.com/25840091/208396856-8b89ad35-59c4-4b07-9ba7-5e0faf4e8d8b.png)

Just insert this line in Dockerfile, before the `ln` command.

**Comment by JoelGMSec** [comment]
> Solution: ![imagen](https://user-images.githubusercontent.com/25840091/208396856-8b89ad35-59c4-4b07-9ba7-5e0faf4e8d8b.png)
> 
> Just insert this line in Dockerfile, before the `ln` command.

Solved with this, thanks!

**Comment by chromeheartbeat** [comment]
Thanks Everyone. Merry Christmas
