### ISSUE TITLE
Browser doesn't load the page [EvilnoVNC]

### ISSUE THREAD

**Issue by Tc-XoNoR** [JoelGMSec/EvilnoVNC#12]
I installed Docker (that seems to run correclty; intallation guide: https://docs.docker.com/engine/install/ubuntu/) and Chromium as required. Followed the guide (https://darkbyte.net/robando-sesiones-y-bypasseando-2fa-con-evilnovnc/) on my kali linux, and Ubuntu, neither works.
./start.sh runs correclty, but when i type localhost:5980 on my local browser it display a connection error:
Firefox can't establish a connection with local server localhost:5980.

Ubuntu:
22.10
Kernel Linux 5.19.0-26-generic

Kali-Linux:
2022.3
Kernel Linux 5.18.0-kali5-amd64

Can someone help please? :)

**Comment by chromeheartbeat** [comment]
1. Check if Docker is successfully Built 
     "sudo docker images" : if yes, you should see in your docker container  **Joelgmsec/evilnovnc 874mb**

2. check if your browser java script is enable?

3. you might need to start evilnovnc with this command 
      sudo docker start evilnovnc

Let me know if this is helpful
cheers

**Comment by Tc-XoNoR** [comment]
> 1. Check if Docker is successfully Built
>    "sudo docker images" : if yes, you should see in your docker container  **Joelgmsec/evilnovnc 874mb**
> 2. check if your browser java script is enable?
> 3. you might need to start evilnovnc with this command
>    sudo docker start evilnovnc
> 
> Let me know if this is helpful cheers

thanks for answering, i appreciate it :)

it doesn't display Joelgmsec/evilnovnc 874mb using  command: "sudo docker images" ,
i tried to launch again the command in a virgin VM: "sudo docker build -t joelgmsec/evilnovnc ."
it display an error : 

ln: /usr/bin/python: File exists
The command '/bin/sh -c apk add sudo bash xfce4 xvfb xdpyinfo lightdm-gtk-greeter x11vnc xfce4-terminal chromium python3 py3-pip git openssl curl gcc libc-dev python3-dev &&     ln -s /usr/bin/python3 /usr/bin/python &&     echo 'CHROMIUM_FLAGS="--disable-gpu --disable-software-rasterizer --disable-dev-shm-usage --kiosk --no-sandbox --password-store=basic"' >> /etc/chromium/chromium.conf &&     dbus-uuidgen > /var/lib/dbus/machine-id' returned a non-zero code: 1

Do you know how to solve? thx :D

**Comment by chromeheartbeat** [comment]
It may be that your tests are failing on an assertion and that failed assertion may be throwing the non zero error code or problem with the docker build.

Exit code 1
Tests were collected and run but some of the tests failed.

Exit Code 1 indicates that a container shut down, either because of an application failure or because the image pointed to an invalid file.

I posted early today about the issues

**Comment by Tc-XoNoR** [comment]
> It may be that your tests are failing on an assertion and that failed assertion may be throwing the non zero error code or problem with the docker build.
> 
> Exit code 1 Tests were collected and run but some of the tests failed.
> 
> Exit Code 1 indicates that a container shut down, either because of an application failure or because the image pointed to an invalid file.
> 
> I posted early today about the issues


So you got same stuff uff..

Let me know if u solve plsss

anyway i will keep an eye on your issue.

Thank in advance!

**Comment by Weesary** [comment]
Solution:
![imagen](https://user-images.githubusercontent.com/25840091/208396856-8b89ad35-59c4-4b07-9ba7-5e0faf4e8d8b.png)

Just insert this line in Dockerfile, before the `ln` command.

**Comment by JoelGMSec** [comment]
> Solution: ![imagen](https://user-images.githubusercontent.com/25840091/208396856-8b89ad35-59c4-4b07-9ba7-5e0faf4e8d8b.png)
> 
> Just insert this line in Dockerfile, before the `ln` command.

Added to next release, thanks!

**Comment by Tc-XoNoR** [comment]
thaks to everyone! :D
