### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by bufferof** [JoelGMSec/EvilnoVNC#13]
I got this error while building docker image

![image](https://user-images.githubusercontent.com/90347373/208524093-b48c7823-dc04-4248-9cd3-a3a86a4124c4.png)

**Comment by chromeheartbeat** [comment]
issue solved here 

https://user-images.githubusercontent.com/25840091/208396856-8b89ad35-59c4-4b07-9ba7-5e0faf4e8d8b.png
