### ISSUE TITLE
Des and Md5 files not found

### ISSUE THREAD

**Issue by thib-d** [JoelGMSec/EvilnoVNC#17]
Hey, 
I followed the doc 
`
git clone https://github.com/JoelGMSec/EvilnoVNC
cd EvilnoVNC ; sudo chown -R 103 Downloads
sudo docker build -t joelgmsec/evilnovnc .
./start.sh 1280x720x16 http://example.com

`

And in the browser session I get an error: 

GET http://localhost:5980/core/des.js 404 (File not found)
 GET http://localhost:5980/core/util/md5.js net::ERR_ABORTED 404 (File not found)

Is someone know why ?

<img width="748" alt="image" src="https://user-images.githubusercontent.com/23265982/213779198-0b4099f4-27f0-4245-a293-39f309a4764f.png">

**Comment by gas4jews** [comment]
I doubt JoelGM cares about this tool anymore

**Comment by JoelGMSec** [comment]
> I doubt JoelGM cares about this tool anymore

Of course, I will soon release the new version with many improvements and these bugs fixed.

Regards!

**Comment by gas4jews** [comment]
> > I doubt JoelGM cares about this tool anymore
> 
> Of course, I will soon release the new version with many improvements and these bugs fixed.
> 
> Regards!

Woah you alive, ngl evilnovn still better than evilginx with shitty domain linking feature

**Comment by t3chn0t3s** [comment]
There were some updates to noVNC within the last 3 weeks.  The noVNC/core/rfb.js file, in the container, tries to import libraries from locations they no longer exist in and there other changes as well. 

I found that one work around was to update rfb.js in the docker container and move some files around.  There is actually an updated version of the rfb.js file located, on the host, in the EvilNoVNC/Files directory.  You should be able to copy it over to your container and move around the necessary files using the following commands: 

```shell
# Assumes you only have one container running and you are inside the EvilnoVNC directory
sudo docker cp Files/rfb.js $(docker ps -q):/home/user/noVNC/core/rfb.js
sudo docker exec $(docker ps -q) cp noVNC/core/crypto/des.js noVNC/core/des.js
sudo docker exec $(docker ps -q) cp noVNC/core/crypto/md5.js noVNC/core/util/md5.js
```

**Comment by andizaa** [comment]
did you fix this?

**Comment by JoelGMSec** [comment]
Fixed! :)
