### ISSUE TITLE
3 observations after initial test

### ISSUE THREAD

**Issue by ratata007** [JoelGMSec/EvilnoVNC#2]
@JoelGMSec First off this is an awesome tool. Below are my observation after testing...

1: End user is not able to input passwords in Upper case/Capital letters.

2: Chromium does not start up in the manner explained in the article after pressing "Ctrl+C". (Screenshot attached) 
<img width="1156" alt="1" src="https://user-images.githubusercontent.com/112831197/188337549-af3e7215-ddf0-4608-9c73-fe0e0a94e47b.png">
<img width="773" alt="2" src="https://user-images.githubusercontent.com/112831197/188337562-f202bd21-ebc6-4fb0-94f3-9ee29dc1ba03.png">

3: Although the cookie saves to the folder, the value's are encrypted.... (Screenshot attached) 
<img width="636" alt="3" src="https://user-images.githubusercontent.com/112831197/188338159-3d71c953-d034-41ac-bf65-99b3db942fae.png">

**Comment by JoelGMSec** [comment]
Solved on last update :)

Thanks for using EvilnoVNC!
