### ISSUE TITLE
Can't Access Localhost:5980 on VPS

### ISSUE THREAD

**Issue by chromeheartbeat** [JoelGMSec/EvilnoVNC#23]
On this new update that doesn't display the port number.  I'm finding it difficult to access my URL. 

I have allowed TCP rule on firewall on 0.0.0.0/0:5980 but I can't still access anything as my page display "This site can’t be reached". 

After starting the EvilnoVNC and I open another terminal to view all port running "sudo netstat -tulpn | grep LISTEN", I can't find EvilnoVNC port running anywhere.

@weesary @JoelGMSec @Antonim22 @harbinc

What am i doing wrong?

**Comment by aleemworu** [comment]
Thanks. Cheers
