### ISSUE TITLE
Not getting port no after url

### ISSUE THREAD

**Issue by uncommonbreed475** [JoelGMSec/EvilnoVNC#26]
Hello good day
As i was using Evilnovnc, i faced this problem where i m not getting port no after url,, like "url: http://localhost" i wanted it with port no like url: http://localhost:8080 or any other  port no, i tried all way possible, like running docker with -p flag and also i tried docker -d -it - p 8080:80 image id, but still fail to get port no after url, here is the picture of my issue please have a look
![IMG20230404035850](https://user-images.githubusercontent.com/98353934/230510232-99a2256c-f38c-4b5a-a572-103580325900.jpg)
And second picture where i tried to use it with port 3000
![IMG20230407040551](https://user-images.githubusercontent.com/98353934/230510258-c948b9bc-6dac-4e8e-bacb-abb1c2e85746.jpg)
Please guide me what did i miss ?? Or any config file i need to edit to get port no after url for outside world Thank You

**Comment by Garysaru** [comment]
> Hello good day As i was using Evilnovnc, i faced this problem where i m not getting port no after url,, like "url: http://localhost" i wanted it with port no like url: http://localhost:8080 or any other port no, i tried all way possible, like running docker with -p flag and also i tried docker -d -it - p 8080:80 image id, but still fail to get port no after url, here is the picture of my issue please have a look ![IMG20230404035850](https://user-images.githubusercontent.com/98353934/230510232-99a2256c-f38c-4b5a-a572-103580325900.jpg) And second picture where i tried to use it with port 3000 ![IMG20230407040551](https://user-images.githubusercontent.com/98353934/230510258-c948b9bc-6dac-4e8e-bacb-abb1c2e85746.jpg) Please guide me what did i miss ?? Or any config file i need to edit to get port no after url for outside world Thank You

you able to solve this yet? i'm having this problems it really got my head fucked up

**Comment by uncommonbreed475** [comment]
It got many errors not ready to use

**Comment by jakefromiowa** [comment]
Same issue here, just generates http://localhost

**Comment by JoelGMSec** [comment]
Currently EvilnoVNC does not need a special port to work (as before), and always generates http://localhost to use it.
Then, you need to point your domain, use Cloudflare or similar if you want HTTPS.
