### ISSUE TITLE
automate page 

### ISSUE THREAD

**Issue by yairdabach1991** [JoelGMSec/EvilnoVNC#27]
Hi , your tool very good but it is not automate.
that resolution page for login when send to target is not match with target device.

**Comment by yairdabach1991** [comment]
solution : when someone is redirected to visit your page you can gain user agent and device type and and set the resolution size which is compatible with target device.

**Comment by yairdabach1991** [comment]
why sometimes does not work?
![Capture](https://github.com/JoelGMSec/EvilnoVNC/assets/135438965/0db23c0d-87b1-424c-b485-4f5d56862529)

**Comment by ms101** [comment]
> why sometimes does not work? ![Capture](https://user-images.githubusercontent.com/135438965/244941687-0db23c0d-87b1-424c-b485-4f5d56862529.PNG)

fixed in PR #31
