### ISSUE TITLE
Can't load Chinese?

### ISSUE THREAD

**Issue by N0el4kLs** [JoelGMSec/EvilnoVNC#3]
I cloned a website containing Chinese, but it looks weird.
Original site
![image](https://user-images.githubusercontent.com/64629436/189400054-86ffaac6-1373-45f7-81ee-36099435c15d.png)
Cloned site
![image](https://user-images.githubusercontent.com/64629436/189400189-4b94a1e9-f0f0-4587-bcf3-d2e9589cba19.png)

**Comment by JoelGMSec** [comment]
Hi,

I'll get on it as soon as possible, thanks for the heads up.

Regards!

**Comment by edwardyeung** [comment]
> Hi,
> 
> I'll get on it as soon as possible, thanks for the heads up.
> 
> Regards!

add an apk in dockerfiles will fix this problem.

RUN apk add wqy-zenhei --update-cache --repository http://nl.alpinelinux.org/alpine/edge/testing --allow-untrusted

this is a font missing error.

**Comment by JoelGMSec** [comment]
Solved :)
