### ISSUE TITLE
Full desktop and root terminal access in running container

### ISSUE THREAD

**Issue by ms101** [JoelGMSec/EvilnoVNC#32]
There is a way to get access to the desktop and root terminals in a running container (tested with latest Firefox and Chromium):

1. (optional) Ctrl+Alt+RightArrowKey switches to another virtual desktop
2. Alt+F2 starts the app launcher, choose xfce4-keyboard-settings
3. choose Application Shortcuts and add a new one
4. as command: chmod 777 /usr/bin/xfce4-terminal
5. as shortcut: Alt+F3
6. save, overwrite shortcut and press Alt+F3
7. then start xfce4-terminal via app launcher (Alt+F2), this also works for starting thunar or xfce4-panel

Now a user has root access to the container, including collected data in /home/user/Downloads:
![2023-09-25_14-52-27_screenshot](https://github.com/JoelGMSec/EvilnoVNC/assets/7735657/b8802e5d-7158-4367-8a03-75be10fa9334)

Possible measures:
- harden XFCE configuration or file permissions
- better avoid a full DE at all (working on it..)

**Comment by ms101** [comment]
PR #33 should fix this

**Comment by JoelGMSec** [comment]
Thanks again @ms101 :)
