### ISSUE TITLE
Running behind a reverse proxy

### ISSUE THREAD

**Issue by JackTheTripperr** [JoelGMSec/EvilnoVNC#38]
Hi Joel,

Is there a quick and easy way for me to configure this to be served over a different port so I could run a reverse proxy with nginx?

Thanks!

Jack

**Comment by JoelGMSec** [comment]
Hi Jack!

1 - You don't need to use a reverse proxy to use the tool.
2 - You can do a NAT to change the external port if you use a VPS or similar, or you can even do it with SOCAT or SSH.
3 - You can also use all kinds of tunnels like Cloudflare, to offer it over HTTPS without having to modify anything.

Thanks for using EvilnoVNC! :)

**Comment by JackTheTripperr** [comment]
Thanks Josh, appreciate the quick response!
