### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by ssl-user-en** [JoelGMSec/EvilnoVNC#4]
I tried running it locally. The script run but it doesn't proxy the website. I tried all the tutorials nothing seems to work. I tried running on AWS ec2 ubuntu instance. Always turns out to be connection reset or we are trying to find the website. Can anyone help?

**Comment by JoelGMSec** [comment]
Hi,

I need more information to help you. Although EvilnoVNC has been tested and designed on Kali Linux, it should work fine on Debian/Ubuntu and its derivatives.

- Have you checked that Docker is installed and working properly?
- Have you checked that port 5980 is not being used by any other application or service?
- Are you running the script with sudo or root permissions?

Regards!

**Comment by rhks** [comment]
Can you add webhook to send results to telegram, email etc?

**Comment by JoelGMSec** [comment]
It's not on my to-do list right now, but I don't rule it out in the future. 
If you have any other ideas, please let me know.

Regards!
