### ISSUE TITLE
redirect after the phishing proccess completes

### ISSUE THREAD

**Issue by trinckvalue** [JoelGMSec/EvilnoVNC#7]
so i was wondering what would happen if the link was sent to a victim then after he enters his email, password and  2fa we get the cookies and stuff but how we can redirect the victim to another site, i mean imagine if he just stays there and he will just stay stuck
there.
it would be pretty interesting if you could add a redirect feature so that when we see that we have cookies it will automatically or manually (via command) redirect him to another website.

**Comment by jcarvajalantigua** [comment]
in this case you can use a third-party tool to configure what is used by proxy manager

**Comment by chromeheartbeat** [comment]
Does anyone knows how I live my localhost to access the link from any devices. 

please Guide?

**Comment by just-hacked** [comment]
> 

use vps and can also setup a reverse proxy to route the traffic
