### ISSUE TITLE
How to live my LocalHost

### ISSUE THREAD

**Issue by chromeheartbeat** [JoelGMSec/EvilnoVNC#9]
Does anyone know how I can live my localhost to access the link from any devices.

Please Guide?

I have tried using Ngrok and it Failed

**Comment by HiredHaxor** [comment]
Use ngrok.

**Comment by aleemworu** [comment]
Can you guide me on the process?

**Comment by chromeheartbeat** [comment]
I have tried using Ngrok and it Failed. can you guide me on it?

**Comment by Antonim22** [comment]
Try using pagekite.me, ngrok may block the account

**Comment by chromeheartbeat** [comment]
After successfully installing pagekite on my kali and running both the pagekite and EvilNOVNC. its seems not to work when i tried visiting the url on my device's browsers

PAGEKITE STARTUP                    
~<> Flying localhost:80 as https://url.pagekite.me/                    
!!! 102.8 - http://url.pagekite.me:80 (FAIL: localhost:80 is down)
!!! 102.8 - http://url.pagekite.me:80 (FAIL: localhost:80 is down)

and EVILNOVNC 
[>] EvilnoVNC Server is running..
[+] URL: http://localhost:5980
[!] Press Ctrl+C at any time to close!
[+] Cookies will updated every 30 seconds..

**Comment by chromeheartbeat** [comment]
**I did this and got response but nothing displays** 

Your webapp is probably listening on IPv6 localhost (::1) and pagekite.py is trying to connect to IPv4 localhost (127.0.0.1).

Forcing your webapp to listen on 127.0.0.1 should fix this.

$ php -S 127.0.0.1:8080
